# Generated by Django 4.0.4 on 2022-06-01 14:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sheet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telegram_user_id', models.BigIntegerField(null=True, unique=True)),
                ('name', models.CharField(max_length=255, null=True)),
                ('phone_number', models.CharField(max_length=255, null=True)),
                ('group_one', models.CharField(default='مغادر', max_length=255)),
                ('group_two', models.CharField(default='مغادر', max_length=255)),
                ('group_three', models.CharField(default='مغادر', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telegram_user_id', models.BigIntegerField(null=True, unique=True)),
                ('telegram_user_name', models.CharField(max_length=255, null=True)),
                ('telegram_first_name', models.CharField(max_length=255, null=True)),
                ('telegram_last_name', models.CharField(max_length=255, null=True)),
                ('telegram_language', models.CharField(max_length=255)),
                ('telegram_is_bot', models.BooleanField(default=False)),
                ('is_admin', models.BooleanField(default=False)),
                ('name', models.CharField(default='None', max_length=100)),
                ('phone_number', models.CharField(default='None', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telegram_group_id', models.BigIntegerField(null=True, unique=True)),
                ('telegram_group_title', models.CharField(max_length=255, null=True)),
                ('telegram_url', models.CharField(max_length=255, null=True, unique=True)),
                ('telegram_counts', models.IntegerField(default=0, null=True)),
                ('telegram_chat_type', models.CharField(max_length=255, null=True)),
                ('start', models.IntegerField(null=True)),
                ('end', models.IntegerField(null=True)),
                ('period', models.CharField(max_length=25, null=True)),
                ('status', models.BooleanField(default=False)),
                ('user_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='tabook.user')),
            ],
        ),
    ]
